import * as React from "react";
import type { HeadFC, PageProps } from "gatsby";
import PageLayout from "../components/page-layout/PageLayout";


const ContactPage: React.FC<PageProps> = () => {
  return (
    <PageLayout>
      <h1>Contact Page</h1>
    </PageLayout>
  );
};

export default ContactPage;

export const Head: HeadFC = () => (
  <>
    <title>Contact | Insightuful IR</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </>
);