import * as React from "react";
import type { HeadFC, PageProps } from "gatsby";
import PageLayout from "../components/page-layout/PageLayout";
import BenefitsSection from "../components/page-sections/homepage/benefits-section/BenefitsSection";
import CTASection from "../components/page-sections/shared/cta-section/CTASection";
import FAQSection from "../components/page-sections/homepage/faq-section/FAQSection";
import HeroSection from "../components/page-sections/homepage/hero-section/HeroSection";
import HowItWorksSection from "../components/page-sections/homepage/how-it-works-section/HowItWorksSection";
import InfoSection from "../components/page-sections/homepage/info-section/InfoSection";
import PopularStocksSection from "../components/page-sections/homepage/popular-stocks/PopularStocksSection";
import SectionDivider from "../components/page-sections/shared/section-divider/SectionDivider";


const HomePage: React.FC<PageProps> = () => {
  return (
    <PageLayout>
      <HeroSection />
      <InfoSection />
      <SectionDivider bgColor="white" />
      <BenefitsSection />
      <PopularStocksSection />
      <SectionDivider />
      <HowItWorksSection />
      <FAQSection />
      <CTASection />
    </PageLayout>
  )
};

export default HomePage;

export const Head: HeadFC = () => (
  <>
    <title>Stock Analysis App for Individual Investors | Insightuful IR</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </>
);
